// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZJwJLpPb0V6ioOeb5vXrybB974vDdAM',
    appId: '1:1020717145318:web:97a8ab2998f476adaeef27',
    messagingSenderId: '1020717145318',
    projectId: 'home-service-c0f6f',
    authDomain: 'home-service-c0f6f.firebaseapp.com',
    storageBucket: 'home-service-c0f6f.firebasestorage.app',
    measurementId: 'G-FDDVBL0EXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-5OvFjmuxxnACJ5LRaf_rJElrf7s8Mx8',
    appId: '1:1020717145318:android:3de9af4c988b7c3faeef27',
    messagingSenderId: '1020717145318',
    projectId: 'home-service-c0f6f',
    storageBucket: 'home-service-c0f6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3-_b4jYUGov579RRcpqup6hwj6-Jg_A',
    appId: '1:1020717145318:ios:8ffa2bc7be81a0d9aeef27',
    messagingSenderId: '1020717145318',
    projectId: 'home-service-c0f6f',
    storageBucket: 'home-service-c0f6f.firebasestorage.app',
    iosBundleId: 'com.homeservice.homeService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw3-_b4jYUGov579RRcpqup6hwj6-Jg_A',
    appId: '1:1020717145318:ios:8ffa2bc7be81a0d9aeef27',
    messagingSenderId: '1020717145318',
    projectId: 'home-service-c0f6f',
    storageBucket: 'home-service-c0f6f.firebasestorage.app',
    iosBundleId: 'com.homeservice.homeService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPZJwJLpPb0V6ioOeb5vXrybB974vDdAM',
    appId: '1:1020717145318:web:b13f17b58d7cc487aeef27',
    messagingSenderId: '1020717145318',
    projectId: 'home-service-c0f6f',
    authDomain: 'home-service-c0f6f.firebaseapp.com',
    storageBucket: 'home-service-c0f6f.firebasestorage.app',
    measurementId: 'G-38VFYNHJZJ',
  );
}
